### ISSUE TITLE
MacPass crashes every time I open it

### ISSUE THREAD

**Issue by nick2585** [mstarke/MacPass#600]
0.6.2 did this for me and now the continuous build also does it for me.

It opens saying MacPass crashed and asks if I want to reopen it. Whatever option I choose it crashes.

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Controller cannot be nil'
terminating with uncaught exception of type NSException
abort() called

**Comment by mstarke** [comment]
That's a rather strange bug. I'll try to investigate. Can you run a debug build so I we can get a better trace?

**Comment by mstarke** [comment]
Fixed. Will be available as continuous shortly

**Comment by nick2585** [comment]
Thanks!!! I was bummed when I had to go back to KyPass companion!

**Comment by nick2585** [comment]
Unfortunately the same problem is still occurring...

Process:               MacPass [7012]
Path:                  /Applications/MacPass.app/Contents/MacOS/MacPass
Identifier:            com.hicknhacksoftware.MacPass
Version:               0.6.2 (20170617070636-continuous)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MacPass [7012]
User ID:               501

Date/Time:             2017-06-19 11:09:47.783 -0500
OS Version:            Mac OS X 10.12.5 (16F73)
Report Version:        12
Anonymous UUID:        F8C30E80-94C2-58DE-68CA-3596587D884C

Sleep/Wake UUID:       58EC0F83-C6AA-4052-97DB-4C50712EBB77

Time Awake Since Boot: 10000 seconds
Time Since Wake:       7500 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Controller cannot be nil'
terminating with uncaught exception of type NSException
abort() called

**Comment by mstarke** [comment]
Are you using the newly release contiuous build? Can you take a look at the about screen? Does the crash occur directly after launch?

**Comment by mstarke** [comment]
And again, can I supply you a debug version so you can give a bit more feedback about the crash. This short expert is nothing I can work with.

**Comment by nick2585** [comment]
Yeah I will run the debug version if you supply it. Thanks!

**Comment by nick2585** [comment]
Ok, it just started working now! thanks!

**Comment by mstarke** [comment]
That is rather strange since you crash happend with the current build. I have no clue what fixed you crash and what triggers it.

**Comment by mstarke** [comment]
If the crash still happens, please reopen the issue. Otherwise I'll regard this as fixed.
